services:
  - type: web
    name: localmarket-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: mysql://3rwEX3bM6GgimVG.root:HxpS7cifPX2bMUJ8@gateway01.us-east-1.prod.aws.tidbcloud.com:4000/IF0_41409995_Local_market
      - key: MAIL_USERNAME
        value: tu_correo@gmail.com
      - key: MAIL_PASSWORD
        value: tu_contraseña_de_aplicacion
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True