services:
  - type: web
    name: localmarket-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: localmarket-db
          property: connectionString
      - key: MAIL_USERNAME
        sync: false  # Lo configurarás manualmente en el dashboard
      - key: MAIL_PASSWORD
        sync: false  # Lo configurarás manualmente en el dashboard

databases:
  - name: localmarket-db
    databaseName: localmarket
    user: localmarket_user
    plan: free