services:
  - type: static
    name: localmarket
    runtime: static
    rootDir: pagina web  # <-- AÑADE ESTA LÍNEA
    buildCommand: echo "No build needed"
    publishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /inicio.html
