services:
  - type: web
    name: localmarket
    runtime: static
    buildCommand: echo "No build needed"
    staticPublishPath: .  # La carpeta raíz donde están tus archivos
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /inicio.html